# Generated by Django 4.1.1 on 2022-09-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice_app', '0002_alter_balancesheet_bs_id_alter_category_cat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_Balancesheet',
            fields=[
                ('bs_id', models.IntegerField(primary_key=True, serialize=False)),
                ('light_bill', models.FloatField()),
                ('emp_salary', models.FloatField()),
                ('monthly_rent', models.FloatField()),
                ('miscellaneous', models.FloatField()),
                ('bs_date', models.DateField()),
                ('customerinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.customerinvoice')),
                ('purchaseorderdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.purchaseorderdetails')),
            ],
        ),
    ]
